const rootPathKey = 'rootPath'
//发布localstorage key
const PUBLISH_PROJECT_KEY = 'publishProject'

enum callFnName {
  getState = "getState",
  GetSysConfig = "GetSysConfig",
  SaveSysConfig = "SaveSysConfig",
  ShowDirSelect = "ShowDirSelect",
  GetPrinterList = "GetPrinterList",
  GetDevcieConfigs = "GetDevcieConfigs",
  SaveDevcieConfig = "SaveDevcieConfig",
  DeleteDevcieConfig = "DeleteDevcieConfig",
  getSupportDevices = "getSupportDevices",
  GetCategoryNodes = "GetCategoryNodes",
  saveCategoryNode = "saveCategoryNode",
  deleteCategoryNode = "deleteCategoryNode",
  GetCategoryDatas = "GetCategoryDatas",
  saveCategoryData = "saveCategoryData",
  deleteCategoryData = "deleteCategoryData",
  GetDataConfigs = "GetDataConfigs",
  saveDataConfig = "saveDataConfig",
  deleteDataConfig = "deleteDataConfig",
  initDataConfig = "initDataConfig",
  GetFormulaConfigs = "GetFormulaConfigs",
  getFormulaDatas = "getFormulaDatas",
  GetProductStatistics = "GetProductStatistics",
  GetProductLogs = "GetProductLogs",
  deleteProductHistory = "deleteProductHistory",
  GetSerialNos = "GetSerialNos",
  SaveSerialNo = "SaveSerialNo",
  DeleteSerialNo = "DeleteSerialNo",
  getNewSerialNo = "getNewSerialNo",
  getFullCollectPoints = "getFullCollectPoints",
  GetCpkData = "GetCpkData",
  startSpcSystem = 'startSpcSystem',
  CloseApp = 'CloseApp',
  showDevTools = 'showDevTools',
  closeSpcSystem = `closeSpcSystem`,
  StartCollect = `StartCollect`,
  openDevTool = `openDevTool`,
  InitService = `InitService`,
  InitDevice = `InitDevice`,
  GetDataAddresses = `GetDataAddresses`,
  GetDevcieDrivers = `GetDevcieDrivers`,
  SaveDataAddress = `SaveDataAddress`,
  DeleteDataAddress = `DeleteDataAddress`,
  GetDataGroups = `GetDataGroups`,
  SaveDataGroup = `SaveDataGroup`,
  EnableDataGroup = `EnableDataGroup`,
  DeleteDataGroup = 'DeleteDataGroup',
  GetDataAddressesWithIds = `GetDataAddressesWithIds`,
  SaveDataGroupOnlyName = `SaveDataGroupOnlyName`,
  EnableFormulaConfig = `EnableFormulaConfig`,
  DeleteFormulaConfig = `DeleteFormulaConfig`,
  GetFormulaFields = `GetFormulaFields`,
  GetFormulaParams = `GetFormulaParams`,
  SaveFormulaParams = `SaveFormulaParams`,
  DeleteProductHistorys = `DeleteProductHistorys`,
  DeleteProductHistory = `DeleteProductHistory`,
  ShaftCollect = `ShaftCollect`,
  GetRealtimeData = `GetRealtimeData`,
  GetChartDataAddress = `GetChartDataAddress`,
  GetChartData = `GetChartData`,
  GetShowDataAddress = `GetShowDataAddress`,
  SaveFormulaConfig = `SaveFormulaConfig`, activeFormulaConfig = 'activeFormulaConfig', GetProductHistorys = 'GetProductHistorys', StopCollect = "StopCollect",
  getSpanCollectPoints = `getSpanCollectPoints`, getNormalDistribution = 'getNormalDistribution', ClearCollect = 'ClearCollect',
  getFFT = `getFFT`, showKeyBoard = `showKeyBoard`, initKeyboardConfig = `initKeyboardConfig`, checkRegister = `checkRegister`, getMachineCode = `getMachineCode`, getRegisterState = `getRegisterState`, getRegisterCode = `getRegisterCode`, KeyPress = `KeyPress`, KeyDown = `KeyDown`, KeyUp = `KeyUp`, getLastPoint = `getLastPoint`
}

export {
  rootPathKey, PUBLISH_PROJECT_KEY, callFnName
}